# Generated by Django 5.2.8 on 2025-11-13 16:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('crop_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=256)),
                ('crop_image', models.ImageField(blank=True, null=True, upload_to='crop/image/')),
                ('crop_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('Description', models.TextField(max_length=200)),
                ('harvested_time', models.DateField()),
                ('location', models.TextField(max_length=150)),
            ],
        ),
    ]
