# Generated by Django 5.2.8 on 2025-12-03 09:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='qr_code_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='qr_code_image'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='screenshot',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='screenshot'),
        ),
    ]
