# Generated by Django 5.2.8 on 2025-12-03 10:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_contractorprofile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='aadhar_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='aadhar_image'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='signature',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='signature'),
        ),
    ]
