# Generated by Django 5.2.8 on 2025-11-21 08:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='image',
        ),
        migrations.CreateModel(
            name='RatingImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='rating/image/')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_images', to='ratings.rating')),
            ],
        ),
    ]
