# Generated by Django 5.2.8 on 2025-12-03 09:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_remove_rating_image_ratingimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
