# Generated by Django 5.2.8 on 2025-12-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='admin_notes',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='priority',
            field=models.CharField(default='Low', max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
