# Generated by Django 5.2.8 on 2025-11-13 16:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('demand_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=256)),
                ('crop_price', models.IntegerField()),
                ('contact_no', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(max_length=200)),
                ('location', models.TextField(max_length=150)),
                ('harvested_time', models.DateField()),
            ],
        ),
    ]
