# Generated by Django 5.2.8 on 2025-11-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='pdf_document',
            field=models.FileField(blank=True, null=True, upload_to='contracts_pdfs/'),
        ),
        migrations.DeleteModel(
            name='ContractDoc',
        ),
    ]
