# Generated by Django 5.2.8 on 2025-12-03 09:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_contract_pdf_document_delete_contractdoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprogress',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
