# Generated by Django 5.2.8 on 2025-12-03 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_alter_farmerprogress_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='pdf_document',
        ),
    ]
